In [1]:
#Shape of Array
import numpy as np
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)


(3,)
int32


In [2]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)


float64


In [3]:
### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c.shape)


(2, 3)


In [4]:
### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)


(2, 2, 3)


In [5]:
#To check your installed version of Numpy use the command
print (np.__version__)

1.14.3


In [9]:
#NumPy Array
myPythonList = [1,9,8,3]
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 9, 8, 3])

In [10]:
#Mathematical Operations on an Array
numpy_array_from_list + 10

array([11, 19, 18, 13])

In [12]:
#numpy zero
import numpy as np
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [13]:
#numpy zero with datatype
import numpy as np
np.zeros((2,2), dtype=np.int16)


array([[0, 0],
       [0, 0]], dtype=int16)

In [17]:
#numpy one 2D Array with datatype
import numpy as np
np.ones((1,2,3), dtype=np.int16)
      
       


array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [18]:
#numpy Reshape Data
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
#Flatten Data
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [21]:
#numpy.hstack() and numpy.vstack() in Python
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))


Horizontal Append: [1 2 3 4 5 6]


In [22]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))


Vertical Append: [[1 2 3]
 [4 5 6]]


In [24]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)			


[5.46225585 4.51869167 5.47036791 4.72791695 4.80770307 5.2059986
 4.49006245 4.70076343 4.98110212 3.61199048]


In [26]:
#6.	numpy.asarray() in Python 
import numpy as np
A = np.matrix(np.ones((4,4)))	
np.array(A)[2]=2
print(A)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
np.asarray(A)[2]=2
print(A)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [29]:
#numpy.arange() in Python 
import numpy as np
np.arange(1, 11)



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
import numpy as np
np.arange(1, 14, 4)


array([ 1,  5,  9, 13])

In [32]:
#numpy.linspace() and numpy.logspace() in Python 
import numpy as np
np.linspace(1.0, 5.0, num=10)


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [40]:
#LogSpace
import numpy as np
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [41]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	


16

In [43]:
#Indexing and Slicing NumPy Arrays 
## Slice
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)



[[1 2 3]
 [4 5 6]]


In [44]:
## First column
print('First row:', e[0])


First row: [1 2 3]


In [45]:
## Second col
print('Second row:', e[1])


Second row: [4 5 6]


In [46]:
print('Second column:', e[:,1])

Second column: [2 5]


In [48]:
## Second Row, two values
print(e[1, :2])


[4 5]


In [49]:
#Consider the following Array
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)


[4.67381415 5.8051201  4.64868198 5.30895172 3.78068575 4.54767183
 4.09065653 5.80456754 5.52112112 3.95580918]


In [50]:
#Statistical function
### Min 
print(np.min(normal_array))


3.7806857451996967


In [51]:
### Max 
print(np.max(normal_array))


5.805120102785911


In [52]:
### Mean 
print(np.mean(normal_array))


4.813707990306423


In [53]:
### Median
print(np.median(normal_array))


4.661248063850821


In [54]:
### Sd
print(np.std(normal_array))


0.7179072485863599


In [55]:
#numpy.dot(): Dot Product in Python using Numpy
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)


14

In [56]:
#NumPy Matrix Multiplication with np.matmul() Example
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)


array([[19, 22],
       [43, 50]])

In [69]:
#Determinant 2*2 matrix
i = [[5,6],[7,8]]
5*8-7*6 
np.linalg.det(i)



-1.999999999999999