In [1]:
#Single-dimensional Numpy Array
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


In [2]:
#Multi-dimensional Array
a=np.array([(1,2,3),(4,5,6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [3]:
#Python NumPy Array v/s List
import numpy as np
 
import time
import sys
S= range(1000)
print(sys.getsizeof(5)*len(S))
 
D= np.arange(1000)
print(D.size*D.itemsize)


28000
4000


In [4]:
import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)


266.40772819519043
62.399864196777344


In [5]:
#Python NumPy Operations
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)


2
