In [1]:
#Python NumPy Operations
import numpy as np
a = np.array([(1,2,3)])
print(a.itemsize)


4


In [2]:
import numpy as np
a = np.array([(1,2,3)])
print(a.dtype)


int32


In [3]:
import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)


6
(1, 6)


In [4]:
#reshape
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)


[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [5]:
#slicing
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])


3


In [6]:
#slicing
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])


[3 5]


In [7]:
#slicing
import numpy as np
a=np.array([(8,9),(10,11),(12,13)])
print(a[0:2,1])


[ 9 11]


In [8]:
#linspace 
import numpy as np
a=np.linspace(1,3,10)
print(a)


[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [9]:
#max/ min
import numpy as np
 
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())



1
3
6


In [10]:
#axis
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))


[4 6 8]


In [11]:
#square Root & Standard Deviation
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))



[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [12]:
#AdditionOperation
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)



[[ 2  4  6]
 [ 6  8 10]]


In [13]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)


[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#vertical
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))


[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]
